[workspace]
members = ["nexsock-protocol-core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Emil Schütt <emil.schutt@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/retrokiller543/nexsock2"
repository = "https://github.com/retrokiller543/nexsock2"
